src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Faker\Provider\DateTime;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     * 
     */
    private $Ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Veuillez saisir une date au bon format")
     * @Assert\GreaterThan("today", message="La date d'arrivé doit être ultérieur à la date du jour !", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Veuillez saisir une date au bon format")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de fin doit être supérieu à celle du debut !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /** 
     * Callbak qu'on appel à chaque enregistrement
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }
        //calcule du prix total
        if (empty($this->amount)) {
            //prix de l'annonce * nombre de jre
            $this->amount = $this->Ad->getPrice() * $this->getDuration();
        }
    }
    /**
     * Permet de recuperer un tableau des jours qui correspond à ma reservation
     *
     * @return array Un tableau d'objet dateTime
     */
    public function getDays()
    {
        $result = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );
        $days = array_map(function ($daysTimestamp) {
            return new \DateTime(date('Y-m-d', $daysTimestamp));
        }, $result);
        return $days;
    }
    //calcule la durée
    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    //
    public function isBookableDates()
    {
        //1 )il faut connaitre les dates impossible à reserver
        $notAvalableDays = $this->Ad->getNotAvalableDays();
        //2) il faut comparer les dates choisies avec les dates impossible
        $bookingDays = $this->getDays();

        $formtDays = function ($day) {
            return $day->format('Y-m-d');
        };
        //On boucle pour avoir un tableau qui contient des chaines des caracteres de mes journées disponible
        $days = array_map($formtDays, $bookingDays);

        //on boucle pour avoir les jours non disponible
        $notAvalable = array_map($formtDays, $notAvalableDays);

        foreach ($days as $day) {
            if (array_search($day, $notAvalable) !== false) return false;
        }
        return true;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->Booker;
    }

    public function setBooker(?User $Booker): self
    {
        $this->Booker = $Booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->Ad;
    }

    public function setAd(?Ad $Ad): self
    {
        $this->Ad = $Ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;


class BookingType extends ApplicationType
{
    private $transformer;
    public function __construct(FrenchToDateTimeTransformer $tranfromer)
    {
        $this->transformer = $tranfromer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', TextType::class, $this->getConfiguration("Date d'arrivée", "Date d'entrée"))
            ->add('endDate', TextType::class, $this->getConfiguration("Date Fin", "Date de départ"))
            ->add('comment', TextareaType::class, $this->getConfiguration(false, "Description de votre message", ["required" => false]));

        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups' => [
                'Default', 'front'
            ]
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     */
    public function Book(Ad $ad, Request $request, ObjectManager $manager)
    {
        $book = new Booking();
        $form = $this->createForm(BookingType::class, $book);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();

            $book->setBooker($user);
            $book->setAd($ad);
            //Si les dates ne sont pas bon ou pas disponible, erreur
            if (!$book->isBookableDates()) {
                $this->addFlash("warning", "Les dates que vous avez choisie, ne sont pas disponibles");
            } else {
                //Sinon enregistrement et redirection
                $manager->persist($book);
                $manager->flush();
                return $this->redirectToRoute('booking_show', [
                    'id' => $book->getId(),
                    'widthAlert' => true
                ]);
            }
        }
        return $this->render('booking/book.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * Permet d'afficher la page de reservation
     * @Route("/booking/{id}", name="booking_show")
     *
     * @param Booking $booking
     * @return Response
     */
    public function show(Booking $booking, Request $request, ObjectManager $manager)
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setAd($booking->getAd())
                ->setAuthor($this->getUser());
            $manager->persist($comment);
            $manager->flush();
            $this->addFlash('success', 'Votre commentaire est bien envoyé');
        }
        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link href="/css/bootstrap-datepicker.min.css" rel="stylesheet">
{% endblock %}
{% block title %}Reservations l'annonce:
    {{ad.title}}
{% endblock %}

{% block body %}
    <div class="container">
        {{form_start(form)}}
        <h1>Rserver pour l'annonce:
            {{ad.title}}</h1>
        <div class="alert alert-light">
            <p>Vous êtes sur le point de reserver l'annonce de
                <strong>{{ad.author.firstName}}
                    {{ad.author.lastName}}</strong>
            </p>
            <div class="row">
                <div class="col">{{form_row(form.startDate)}}</div>
                <div class="col">{{form_row(form.endDate)}}</div>

            </div>
            <h4>Montant du séjour:
                <span class="" id="amount">...</span>
                &euro;</h4>
            <span id="days">0</span>
            nuit(s) à
            {{ad.price}}
            / nuit
            <h2>Vous avez un commentaires ?</h2>
            {{form_row(form.comment)}}

        </div>
        <h4 mt-3>Vous avez terminé !</h4>
        <button class="btn btn-success" type="submit">Je reserve !</button>
        {{form_end(form)}}
    </div>
{% endblock %}
{% block javascripts %}
    <script>
        $(document).ready(function () {
            $("#booking_startDate,#booking_endDate").datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: [{% for day in ad.getNotAvalableDays %}"{{ day.format('d/m/Y') }}",{% endfor %}],
                startDate: new Date()
            });
            $("#booking_startDate,#booking_endDate").on('change', calculateAmount);
        });

        function calculateAmount() { // on chope les dates
            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const DAY_TIME = 24 * 60 * 60 * 1000;

            if (startDate && endDate && startDate < endDate) {
                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DAY_TIME;
                const amount = days * {{ ad.price }};
                $("#days").text(days);
                $("#amount").text(amount.toLocaleString('fr-FR'));
            }
        }
    </script>

{% endblock %}

templates/booking/show.html.twig
{% extends "base.html.twig" %}
{% block title %}Reservation numero:
    {{booking.id}}
{% endblock %}
{% block body %}
    {% set ad = booking.ad %}
    {% set author = ad.author %}
    <div class="container">
        <h1>Votre reservation n°:
            {{booking.id}}</h1>
        {% if app.request.query.get('widthAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">Bravo !</h4>
                <p>votre reservation aupres de
                    <strong>
                        <a href="{{path('user_show',{'slug':author.firstName})}}">{{author.firstName}}
                            {{author.lastName}}</a>
                    </strong>
                    pour l'annonce
                    <strong>
                        <a href="{{path('ads_show',{'slug':ad.slug})}}">{{ad.title}}</a>
                    </strong>
                    a bien était prise en compte

                </p>
            </div>
        {% endif %}
        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Détails</h2>
                    <dl class="row">

                        <dt class="col-md-4">numéro</dt>
                        <dd class="col-md-8">{{booking.id}}</dd>
                        <dt class="col-md-4">Date Arrivée</dt>
                        <dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{booking.endDate| date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{booking.duration}}</dd>
                        <dt class="col-md-4">Montant total</dt>
                        <dd class="col-md-8">{{booking.amount}}
                            &euro;</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{booking.comment | default('Pas de commentaire')}}</dd>
                    </dl>
                    <hr>
                    <h2 class="alert-heading">Votre hôte</h2>
                    <div class="row mb-3">
                        <div class="col-3">
                            <img src="{{author.picture}}" class="avatar avatar-meduim" alt=""></div>
                        <div class="col-9">
                            <h4>
                                <a href="{{path('user_show',{'slug':author.slug})}}">{{author.firstName}}
                                    {{author.lastName}}</a>
                            </h4>
                            <span class="badge badge-primary">{{author.ads|length}}
                                annonces</span>
                        </div>

                    </div>
                    {{author.description | raw}}
                    <a href="{{path('user_show', {'slug': author.slug})}}" class="btn btn-primary">plus d'info sur
                        {{author.firstName}}</a>
                </div>
                <div class="alert alert-light">
                    {% if date() > date(booking.endDate) %}
                        <h2 class="alert-heading">Votre avis comptes !</h2>
                        {% set comment = booking.Ad.getCommentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <blockquote>{{comment.content}}</blockquote>
                            <strong>Note:
                            </strong>
                            {% include "partials/rating.html.twig" with {'rating': comment.rating} %}
                        {% else %}
                            {{form_start(form)}}
                            {{form_widget(form)}}
                            <button class="btn btn-success" type="submit">Confirmer !</button>
                            {{form_end(form)}}
                        {% endif %}
                    {% else %}
                        <p>Vous ne pouvez pas encore noté cette annonce tant que votre voyage n'est pas terminé !</p>
                    {% endif %}
                </div>
            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h2 class="alert-heading">Votre hébergement</h2>
                    <h4>
                        <a href="{{path('ads_show',{'slug':ad.slug})}}">{{ad.title}}</a>
                    </h4>
                    <img src="{{ad.coverImage}}" alt="" class="img-fluid">
                    {{ad.content | raw}}
                    <a href="{{path('ads_show', {'slug': ad.slug})}}" class="btn btn-primary">Plus d'information</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}