src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une autre annonce possède deja ce titre, merci de le modifier"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10,max=255,minMessage="le titre doit faire 10 caractères minimuim",maxMessage="le titre ne doit pas dépassé 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(min=20,minMessage="Votre introduction doit avoir plus de 20 caractères!")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description doit avoir plus de 100 caractères !")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $romms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="Ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialier le slug avant de persister
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * cette méthode verifie si un user a deja un commentaire
     *
     * @return void
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment) {
            if ($comment->getAuthor() == $author) {
                return $comment;
            }
        }
        return null;
    }

    /**
     * Cette méthode nous calcul la moyenne des notes
     *
     * @return float
     */
    public function getAvgRatings()
    {
        //cacluler la sommes des notations
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        }, 0);

        //faire la divsion pour avoir la moyenne
        if (count($this->comments) > 0) return $sum / count($this->comments);
        return 0;
    }

    /**
     * Cette méthode retourne les jours qui sont pas disponible
     *
     * @return array Un tableau de dateTime
     */
    public function getNotAvalableDays()
    {
        $notAvalableDays = [];
        foreach ($this->bookings as $booking) {
            //Calculer les jours qui existe entre la date de depart et d'arriver
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );

            $days = array_map(function ($daysTimestamp) {
                return new \DateTime(date('Y-m-d', $daysTimestamp));
            }, $resultat);

            $notAvalableDays = array_merge($notAvalableDays, $days);
        }
        return $notAvalableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(?string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRomms(): ?int
    {
        return $this->romms;
    }

    public function setRomms(int $romms): self
    {
        $this->romms = $romms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AnnonceType;
use App\Repository\AdRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ad_index")
     */
    public function index(AdRepository $repo)
    {
        $ads = $repo->findAll();
        return $this->render('ad/index.html.twig', [
            'ads' => $ads,
        ]);
    }

    /**
     * Permet de créer une annonce
     * 
     * @Route("/ads/new", name="ads_create")
     * @IsGranted("ROLE_USER")
     *
     * @return Response
     */
    public function create(ObjectManager $manager, Request $request)
    {
        $ad = new Ad();

        $form = $this->createForm(AnnonceType::class, $ad);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }
            //lier un utilisateur à une annonce
            $ad->setAuthor($this->getUser());
            $manager->persist($ad);
            $manager->flush();
            $this->addFlash(
                'success',
                "Votre annonce <strong> </strong> est enregistrée avec succès !"
            );
            return $this->redirectToRoute('ads_create');
        }
        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * permet de d'afficher le formulaire d'edition 
     * @Route("/ads/{slug}/edit", name="ads_edit")
     * On verifique l'utilisateur est connecté et qu'il est l'auteur de l'annonce
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifié")
     * @return Response
     */
    public function edit(Ad $ad, Request $request,  ObjectManager $manager)
    {
        //on crée un formulaire via le form AnnonceType, et on l'associe avec les données de l'entité $ad
        $form = $this->createForm(AnnonceType::class, $ad);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }
            $manager->persist($ad);
            $manager->flush();
            $this->addFlash('success', 'Modification effectuée avec succès !');
            $this->redirectToRoute('ads_show', ['slug' => $ad->getSlug()]);
        }
        return $this->render(
            'ad/edit.html.twig',
            [
                'form' => $form->createView(),
                'ad' => $ad
            ]
        );
    }

    /**
     * Permet d'afficher une seule annonce
     *
     * @Route("/ads/{slug}", name="ads_show")
     * 
     * @return Response
     */
    public function show(Ad $ad)
    {
        return $this->render('ad/show.html.twig', ['ad' => $ad]);
    }
    /** 
     * Permet de supprimer une annonce
     * @Route("/ads/{slug}/delete/", name="ads_delete")
     * @Security("is_granted('ROLE_USER') and user==ad.getAuthor()",message="Vous n'avez pas le droit d'accèder à cette ressource")
     * @return Response
     */
    public function delete(Ad $ad, ObjectManager $manager)
    {
        $manager->remove($ad);
        $manager->flush();
        $this->addFlash("success", "L'annonce <strong>{$ad->getTitle()}</strong> est supprimée avec succès !");
        return $this->redirectToRoute("ad_index");
    }
}

templates/ad/_ad.html.twig
{% set url = path('ads_show',{'slug':ad.slug}) %}
<div class="col-md-4">
    <div class="card mb-3 bg-light">
        <div class="card-header text-center">
            {{ad.romms}}
            chambres,
            <strong>
                {{ad.price}}
                euros / nuit</strong>
            <br>
            {% if ad.comments|length >0 %}
                {% include "partials/rating.html.twig" with {'rating': ad.avgRatings} %}
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}

        </div>
        <a href="{{url}}}">
            <img alt="Image par ici" src="{{ad.coverImage}}" style="height:200px; width:100%; display:block;"></a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{url}}">
                    {{ad.title}}</a>
            </h4>
            <p class="card-text">
                {{ad.introduction}}
            </p>
            <a href="{{url}}" class="btn btn-secondary">En savoir plus</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{path('ads_edit',{'slug': ad.slug})}}" class="btn btn-secondary">Modifier l'annonce</a>
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _annonce_images_widget %}
    <p>Ici, vous pouvez ajouter vos propres images !</p>
    {{form_widget(form)}}
    <input id="widgets_counter" type="hidden" value="0">
    <button class="btn btn-primary" id="add-image" type="button">
        <i class="fas fa-plus"></i>
        Ajouter une image</button>
{% endblock %}

{% block _annonce_images_entry_row %}
    {{form_widget(form)}}
{% endblock %}
{% block _annonce_images_entry_widget %}
    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{form_widget(form.url)}}
                        {{form_errors(form.url)}}</div>
                    <div class="col">
                        {{form_widget(form.caption)}}
                        {{form_errors(form.caption)}}</div>
                </div>
            </div>
            <div class="col-2">
                <button class="btn btn-danger" data-action="delete" data-target="#block_{{id}}" type="button">X</button>
            </div>
        </div>

    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}
{% block title %}
    Edition d'une annonce
{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}
{% block body %}
    <div class="container">
        <h1>Modifier  une annonce:
            {{ad.title}}</h1>
        {{form_start(form)}}
        {{form_widget(form)}}
        <button class="btn btn-primary" type="submit">Modifier une annonce</button>
        {{form_end(form)}}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="/js/ad.js"></script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Nos annonces!
{% endblock %}
{% block body %}
    <div class="container">
        <h1 class="my-3">Voici nos annonces de nos hotes</h1>
        <div class="row">
            {% for ad in ads %}
                {% include "ad/_ad.html.twig" %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}
{% block title %}
    Création d'une annonce
{% endblock %}
{% form_theme form 'ad/_collection.html.twig' %}
{% block body %}
    <div class="container">
        <h1 class="my-5">Création d'une nouvelle annonce</h1>
        {{form_start(form)}}
        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h3>Information générale</h3>
                    <hr>
                    {{form_row(form.title)}}
                    {{form_row(form.slug)}}
                    {{form_row(form.price)}}
                    {{form_row(form.romms)}}
                </div>
                <div class="alert alert-light">
                    <h3>Détail de l'aonnce</h3>
                    <hr>
                    {{ form_row(form.introduction)}}
                    {{ form_row(form.content)}}

                </div>

            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h3>Image de l'annonce</h3>
                    <hr>
                    {{ form_row(form.coverImage)}}
                    {{form_row(form.images)}}
                </div>
            </div>
        </div>
        <button class="btn btn-primary" type="submit">
            <i class="fas fa-check"></i>
            Créer une nouvelle annonce</button>
        {{form_end(form)}}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="/js/ad.js"></script>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{ad.title}}
{% endblock %}
{% block body %}
    <div class="add-title" style="background-image:url({{ad.coverImage}})">
        <div class="container">
            <h1>
                {{ad.title}}</h1>
            <p>
                {{ad.introduction}}</p>
            <p class="h2">
                <strong>
                    {{ad.romms}}</strong>chambres
            </p>
            <p>
                <strong>pour
                    {{ad.price}}
                    €</strong>
                par nuit</p>
            <a class="btn btn-primary" href="{{path('booking_create',{'slug':ad.slug})}}">Reserver !</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{path('ads_edit',{'slug': ad.slug})}}" class="btn btn-secondary">Modifier l'annonce</a>
                <a href="{{path('ads_delete',{'slug':ad.slug})}}" class="btn btn-danger" onclick="return confirm(`Etes-vous sûr vouloir supprimer l'annonce `: {{ad.title}} ?)">Supprimer l'annonce</a>
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ad.content|raw}}
                <div class="carousel slide" data-ride="carousel" id="carouselExampleIndicators">
                    <ol class="carousel-indicators">
                        {% for image in ad.images %}
                            <li {% if loop.first %} class="active" {% endif %} data-slide-to="{{loop.index0}}" data-target="#carouselExampleIndicators"></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.images %}
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <img alt="First slide" class="d-block w-100" src="{{image.url}}">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>
                                        {{ad.title}}</h5>
                                    <p>
                                        {{image.caption}}</p>
                                </div>
                            </div>
                        {% endfor %}
                        <a class="carousel-control-prev" data-slide="prev" href="#carouselExampleIndicators" role="button">
                            <span aria-hidden="true" class="carousel-control-prev-icon"></span>
                            <span class="sr-only">Précedent</span>
                        </a>
                        <a class="carousel-control-next" data-slide="next" href="#carouselExampleIndicators" role="button">
                            <span aria-hidden="true" class="carousel-control-next-icon"></span>
                            <span class="sr-only">Suivant</span>
                        </a>
                    </div>
                </div>
                <hr>
                {% if ad.comments|length > 0 %}
                    <h2 mb-3>
                        commentaires de nos voyageurs</h2>
                    <div class="alert alert-info">
                        <h4 class="alert-heading">
                            <div class="row align-items-center">
                                <div class="col">Note globale données par nos visiteurs

                                </div>
                                <div class="col">{% include "partials/rating.html.twig" with {"rating":ad.avgRatings} %}<br><small>(Calculée sur
                                        {{ad.comments|length}}
                                        avis )</small>
                                </div>
                            </div>
                        </h4>
                    </div>
                    {% for comment in ad.comments %}
                        <div class="bg-light rounded mb-3 px-3 py-3 ">
                            <strong>{{comment.author.firstName}}
                                {{comment.author.lastName}}
                            </strong>a dit:
                            <blockquote>{{comment.content}}</blockquote>
                            <strong>Note donnée par
                                {{comment.author.firstName}}
                                {{comment.author.lastName}}
                                :</strong>
                            {{comment.rating}}
                            {% include "partials/rating.html.twig" with {"rating":comment.rating} %}
                        </div>
                    {% endfor %}
                {% else %}
                    Cette annonce n'a pas encore reçu des commentaires
                {% endif %}
            </div>
            <div
                class="col-md-4">
                <!-- on crée une variable de twig -->
                {% set a=ad.author %}

                <div class="row mb-6">
                    <div class="col-3">
                        <a href="{{path('user_show',{'slug':a.slug})}}">
                            <img src="{{a.picture}}" class="avatar avatar-meduim" alt="Avatar de {{a.firstName}}"></a>
                    </div>
                    <div class="col">
                        <a href="{{path('user_show', {'slug': a.slug})}}">
                            <h3>{{a.firstName}}
                                {{a.lastName}}</h3>
                        </a>
                        <span class="badge badge-primary">{{a.ads |length }}
                            anonces</span>
                    </div>
                    {{a.description | raw}}
                </div>
            </div>
        </div>
    </div>
</div>{% endblock %}